name: Output Event on issues
on : 
  issues:
    types:
      - opened
jobs:
  Output-Event:
    strategy:
      matrix:
        operating-system: ['ubuntu-latest' , 'windows-latest']
        node-version: [12,14,16]
    runs-on: ${{matrix.operating-system}}
    steps:
        - name: Print the event
          run: echo "${{toJSON(github.event)}}"
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            version: ${{matrix.node-version}}