name: Output Event on issues
on : 
  issues:
    types:
      - opened
jobs:
    Output-Event:
        runs-on: ubuntu-latest
        steps:
           - name: Print the event
             run: echo "${{toJSON(github.event)}}"