name: Output Event on issues
on : 
  issues:
    types:
      - opened
jobs:
  Output-Event:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [12,14,16]
        operating-system: ['ubuntu-latest' , 'windows-latest']
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 12
            operating-system: windows-latest
    runs-on: ${{matrix.operating-system}}
    steps:
        - name: Print the event
          run: echo "${{toJSON(github.event)}}"
        - name: Install NodeJS
          uses: actions/setup-node@v3
          with:
            version: ${{matrix.node-version}}