name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: false
        default: dist
        type: string
    secrets:
        secret-key: 
            description: The name of secret key
            required: false
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}

      - name: List contents
        run: ls

      - name: Output filename
        run: echo "${{secrets.secret-key}}"

      - name: Deploy Project
        run: echo "Deploying..."
