name: Reusable Deploy
on:
  workflow_call:
    inputs:
      artifact-name:
        description: The name of the deployable artifact files
        required: true
        default: dist
        type: string
    secrets:
        secret-key: 
            description: The name of secret key
            required: false
    outputs:
        result:
            value: ${{jobs.Deploy.outputs.outcome}}
jobs:
  Deploy:
    outputs:
        outcome: ${{steps.step-output.outputs.step-result}}
    runs-on: ubuntu-latest
    steps:
      - name: Get Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.artifact-name}}

      - name: List contents
        run: ls

      - name: Output filename
        run: echo "${{secrets.secret-key}}"

      - name: Deploy Project
        uses: ./.github/actions/deploy-to-s3
        env:
         AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
         AWS_SECRET_KEY_ID: ${{secrets.AWS_SECRET_KEY_ID}}
        with:
          bucket: gh-custom-action
          dist-folder: ./dist
    
      - name: Return output
        id: step-output
        run: echo "step-result=success" >> $GITHUB_OUTPUT
