name: Reusable Deploy
on: workflow_call
jobs:
    Deploy:
        runs-on: ubuntu-latest
        steps:
        # - name: Get Artifact
        #   uses: actions/download-artifact@v4
        #   with:
        #     name: test-report

            - name: List contents
              run: ls

            - name: Output filename
              run: echo "${{needs.Build.outputs.script-file}}"

            - name: Deploy Project
              run: echo "Deploying..."